version: 2
jobs:
  test:
    working_directory: ~/saxophone_infochart_back
    docker:
      - image: elixir:1.5.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run:
          name: Install dependencies
          command: |
            mix local.rebar --force
            mix local.hex --force
            mix deps.get
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: mix test

  deploy-dockerhub:
    requires:
      - test
    working_directory: ~/saxophone_infochart_back
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.15.35
      - run:
          name: Push application Docker image
          command: |
            set -x

            aws ecs list-tasks --cluster blog-saxophone-cluster

            docker login --username ${DOCKER_HUB_USERNAME} --password ${DOCKER_HUB_PASSWORD}
            docker build -t saxophone-backend:${CIRCLE_SHA1} .
            docker tag saxophone-backend:${CIRCLE_SHA1} dbastos/saxophone-backend:${CIRCLE_SHA1}
            docker push dbastos/saxophone-backend:${CIRCLE_SHA1}

workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy-dockerhub
